const modules = [
  {
    moduleName: "Role",
    read: "Role-read",
    write: "Role-write",
    all: "Role-all",
    global: "Role-global",
    note: "",
  },
  {
    moduleName: "Department",
    read: "Department-read",
    write: "Department-write",
    all: "Department-all",
    global: "Department-global",
    note: "",
  },
  {
    moduleName: "Holiday",
    read: "Holiday-read",
    write: "Holiday-write",
    all: "Holiday-all",
    global: "Holiday-global",
    note: "",
  },
  {
    moduleName: "Shift",
    read: "Shift-read",
    write: "Shift-write",
    all: "Shift-all",
    global: "Shift-global",
    note: "",
  },
  {
    moduleName: "Staff",
    read: "Staff-read",
    write: "Staff-write",
    all: "Staff-all",
    global: "Staff-global",
    note: "",
  },
  {
    moduleName: "Attendance",
    read: "Attendance-read",
    write: "Attendance-write",
    all: "Attendance-all",
    global: "Attendance-global",
    note: "",
  },
  {
    moduleName: "Client",
    read: "Client-read",
    write: "Client-write",
    all: "Client-all",
    global: "Client-global",
    note: "",
  },
  {
    moduleName: "Lead",
    read: "Lead-read",
    write: "Lead-write",
    all: "Lead-all",
    global: "Lead-global",
    comment: "Lead-comment-update",
    statuses: "Lead-status-update",
    assign: "Lead-assign",
    note: "",
  },
  {
    moduleName: "Inquiry",
    read: "Inquiry-read",
    write: "Inquiry-write",
    all: "Inquiry-all",
    global: "Inquiry-global",
    comment: "Inquiry-comment-update",
    statuses: "Inquiry-status-update",
    assign: "Inquiry-assign",
    note: "",
  },
  {
    moduleName: "Category",
    read: "Category-read",
    write: "Category-write",
    all: "Category-all",
    global: "Category-global",
    note: "",
  },
  {
    moduleName: "Comment",
    read: "Comment-read",
    write: "Comment-write",
    all: "Comment-all",
    global: "Comment-global",
    note: "",
  },
];
module.exports = modules;
